from typing import List, Literal
from pydantic import BaseModel, Field

class RawTopic(BaseModel):
    """
    Schema representing a raw news item or paper scraped from technical sources.
    """
    title: str = Field(..., description="The title of the scraped news item or paper")
    summary: str = Field(..., description="A short summary, abstract, or snippet of the content")
    url: str = Field(..., description="The original source URL of the item")
    source_name: str = Field(..., description="The name of the source (e.g., 'arXiv', 'HackerNews', 'RSS')")


class EditorialDecision(BaseModel):
    """
    Schema representing the LLM persona's editorial evaluation of a topic.
    """
    decision: Literal["PUBLISH", "REJECT"] = Field(
        ..., 
        description="The decision to either publish or reject the topic based on the persona filters"
    )
    score: int = Field(
        ..., 
        ge=1, 
        le=10, 
        description="Priority/relevance score from 1 (lowest) to 10 (highest)"
    )
    reason: str = Field(
        ..., 
        description="The detailed reasoning behind the editorial decision"
    )


class GeneratedPost(BaseModel):
    """
    Schema representing the final structured output generated by the LLM for publishing.
    """
    title: str = Field(..., description="The curated, publication-ready title for the post")
    content: str = Field(..., description="The full, formatted body content of the post (Markdown supported)")
    selection_reason: str = Field(..., description="Brief summary of why this specific post was chosen")
    why_relevant_now: str = Field(..., description="Timely context highlighting why this topic is relevant today")
    sources: List[str] = Field(..., default_factory=list, description="List of source URLs reference material")
